--6
SELECT CUSTOMER_NUM, CUSTOMER_NAME
FROM CUSTOMER 
WHERE CUSTOMER_NUM NOT IN (SELECT CUSTOMER_NUM
						 FROM ORDERS
						 WHERE ORDER_DATE = '2015-10-15')

--Can't write it these ways, different results. Customer may have placed an order on another date
SELECT CUSTOMER_NUM, CUSTOMER_NAME
FROM CUSTOMER 
WHERE CUSTOMER_NUM IN (SELECT CUSTOMER_NUM
						 FROM ORDERS
						 WHERE ORDER_DATE <> '2015-10-15')

SELECT C.CUSTOMER_NUM, C.CUSTOMER_NAME
FROM CUSTOMER C INNER JOIN ORDERS O ON C.CUSTOMER_NUM = O.CUSTOMER_NUM
WHERE O.ORDER_DATE <> '2015-10-15'

--7
SELECT O.ORDER_NUM, O.ORDER_DATE, I.ITEM_NUM, I.DESCRIPTION, I.CATEGORY
FROM ORDERS O INNER JOIN ORDER_LINE L ON O.ORDER_NUM = L.ORDER_NUM
	INNER JOIN ITEM I ON L.ITEM_NUM = I.ITEM_NUM

--8
SELECT O.ORDER_NUM, O.ORDER_DATE, I.ITEM_NUM, I.DESCRIPTION, I.CATEGORY
FROM ORDERS O INNER JOIN ORDER_LINE L ON O.ORDER_NUM = L.ORDER_NUM
	INNER JOIN ITEM I ON L.ITEM_NUM = I.ITEM_NUM
ORDER BY I.CATEGORY, O.ORDER_NUM

--9
SELECT REP_NUM, LAST_NAME
FROM REP
WHERE REP_NUM IN (SELECT REP_NUM
					FROM CUSTOMER
					WHERE CREDIT_LIMIT >= 10000)