--Jessica Hoffman
--A10BA

--Create the Dimension tables
USE CIS31034

CREATE TABLE PRODUCT_DIM
(
PRODUCTID	  INT IDENTITY(1,1) NOT NULL,
PROD_SKU	  VARCHAR(15) NOT NULL,
PROD_DESCRIPT VARCHAR(255),
PROD_TYPE	  VARCHAR(255),
BRAND_ID	  NUMERIC(4,0),
BRAND_NAME	  VARCHAR(100),
BRAND_TYPE	  VARCHAR(20)
)

CREATE TABLE EMPLOYEE_DIM
(
EMPLOYEEID INT IDENTITY(1,1) NOT NULL,
EMP_NUM	   NUMERIC(6,0) NOT NULL,
EMP_FNAME  VARCHAR(20),
EMP_LNAME  VARCHAR(25),
EMP_TITLE  VARCHAR(45),
DEPT_NUM   NUMERIC(5,0),
DEPT_NAME  VARCHAR(50)
)

CREATE TABLE CUSTOMER_DIM
(
CUSTOMERID  INT IDENTITY(1,1) NOT NULL,
CUST_CODE   NUMERIC(38,0) NOT NULL,
CUST_LNAME  VARCHAR(20),
CUST_FNAME  VARCHAR(20),
CUST_STREET VARCHAR(70),
CUST_CITY	VARCHAR(50),
CUST_STATE	CHAR(2),
CUST_ZIP	CHAR(5)
)

CREATE TABLE TIME_DIM
(
TIMEID		INT IDENTITY(1,1) NOT NULL,
INV_DATE	DATE,
YEAR_NUM	INT,
MONTH_NUM	INT,
QUARTER_NUM	INT
)

--Add constraints to the Dimension tables
ALTER TABLE PRODUCT_DIM
ADD CONSTRAINT [PK_PRODUCT_DIM] PRIMARY KEY (PRODUCTID)

ALTER TABLE CUSTOMER_DIM
ADD CONSTRAINT [PK_CUSTOMER_DIM] PRIMARY KEY (CUSTOMERID)

ALTER TABLE EMPLOYEE_DIM
ADD CONSTRAINT [PK_EMPLOYEE_DIM] PRIMARY KEY (EMPLOYEEID)

ALTER TABLE TIME_DIM
ADD CONSTRAINT [PK_TIME_DIM] PRIMARY KEY (TIMEID)


--Create the Fact table
CREATE TABLE FACT_TABLE
(
PRODUCTID		INT NOT NULL,
CUSTOMERID		INT NOT NULL,
EMPLOYEEID		INT NOT NULL,
TIMEID			INT NOT NULL,
LINE_QTY		NUMERIC(18,0),
LINE_PRICE		NUMERIC(8,2)
)

--Add constraints to the Fact table
ALTER TABLE FACT_TABLE
ADD CONSTRAINT FK_PRODUCT FOREIGN KEY (PRODUCTID) REFERENCES PRODUCT_DIM,
	CONSTRAINT FK_CUSTOMER FOREIGN KEY (CUSTOMERID) REFERENCES CUSTOMER_DIM,
	CONSTRAINT FK_EMPLOYEE FOREIGN KEY (EMPLOYEEID) REFERENCES EMPLOYEE_DIM,
	CONSTRAINT FK_TIME FOREIGN KEY (TIMEID) REFERENCES TIME_DIM

ALTER TABLE FACT_TABLE
ADD PRIMARY KEY (PRODUCTID, CUSTOMERID, EMPLOYEEID, TIMEID)

